### ISSUE TITLE
Lightning input mock is missing some methods

### ISSUE THREAD

**Issue by mattgoldspink** [salesforce/lwc-jest#21]
The ones we need specifically are `checkValidity`,`setCustomValidity` and `reportValidity` but it looks like it's missing a few others too.

The other question we had was around the behaviour of the `@api validity` property. From testing at runtime it seems this is always populated with a default object for us, but during testing it's empty. I understand it can be populated during our tests manually, but it would be nice to have it initialized with the same default as the real component.

<img width="992" alt="screen shot 2019-02-12 at 4 36 34 pm" src="https://user-images.githubusercontent.com/415690/52631526-ea386200-2eb6-11e9-8074-d2e59521e1e9.png">

**Comment by trevor-bliss** [comment]
Thanks for the issue and the PR to fix! FWIW I'll be working on a new script to generate the mocks soon that should be much more reliable (the metadata file the mocks are currently generated off of is not 100% up to date). The new script should catch these missing methods going forward.

Regarding the `validity` property, according to the [documentation](https://developer.salesforce.com/docs/component-library/bundle/lightning-input/documentation) this prop should be updated to an object with a bunch of boolean attributes like `badInput`, `customError`, etc. Is that what you're seeing at runtime or is it really an empty object?

**Comment by trevor-bliss** [comment]
@mattgoldspink To clarify though, if you remove the `validity` instantiation from your PR I'll merge it. It's a good fix until the new script is in place.

**Comment by mattgoldspink** [comment]
@trevor-bliss Sorry for the delay, got sucked into other priorities. I fixed the `validity` field and updated the PR. Let me know if there's anything else needed.

**Comment by trevor-bliss** [comment]
@mattgoldspink No worries, thanks again!
