### ISSUE TITLE
Deprecated modules on npm install

### ISSUE THREAD

**Issue by wilsonmar** [salesforce/lwc-jest#27]
I just installed this on my Mac Yosemite running Node v9.11.1. Below is the message returned when I run on a blank folder:

```
npm install @salesforce/lwc-jest --save-dev 
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
```

**Comment by pmdartus** [comment]
Those are known [warnings](https://github.com/facebook/jest/issues/7430), they are caused by transient package dependencies using outdated packages. You can safely ignore them.
