### ISSUE TITLE
Code coverage option is not returning coverage

### ISSUE THREAD

**Issue by muenzpraeger** [salesforce/lwc-jest#31]
When running lwc-jest with the `--coverage` option no code coverage is returned.

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                   |
----------|----------|----------|----------|----------|-------------------|

**Comment by BatemanVO** [comment]
I'm not able to get any code coverage to display still. Instead of showing no values, it just shows zeroes across the board.

![no-coverage](https://user-images.githubusercontent.com/20998142/61817939-92f2d200-ae04-11e9-86da-1730c6776428.PNG)

**Comment by trevor-bliss** [comment]
@BatemanVO Do you have a custom Jest config (jest.config.js) in your project?

**Comment by BatemanVO** [comment]
At the time of that screenshot, I did not. I do now, that's largely a copy-paste from the lwc-recipes example.

![jest-config](https://user-images.githubusercontent.com/20998142/61825476-4bc10d00-ae15-11e9-8788-84a76321bcd6.PNG)

**Comment by joeythomaschaske** [comment]
Started getting this after upgrading to `1.2.1`, I also tried adding `collectCoverageFrom` but it didn't have an effect. Setting `coverageProvider` to `v8` fixed it
