### ISSUE TITLE
Jest in Windows

### ISSUE THREAD

**Issue by Mahakb** [salesforce/lwc-jest#42]
I am not able to use lwc-jest in Windows. Not able to clone it. May be the documentation could be updated.

Can anyone please help me out with this?

**Comment by dilipbhambhani** [comment]
I am also facing the same issue in the Window OS environment during lwc-jest installation. if anyone has a solution so please share with us.

**Comment by muenzpraeger** [comment]
Can you please outline what's not working, like providing error messages etc? Otherwise it's just guesswork.

**Comment by dilipbhambhani** [comment]
> Can you please outline what's not working, like providing error messages etc? Otherwise it's just guesswork.

Hi @muenzpraeger , Thanks for your quick replay. Actually, I have run "npm install @salesforce/lwc-jest --save-dev" command in "Visual Studio" Terminal and it is showing below response with errors: I have also attached debug log file which is created by node.
[2019-03-19T07_56_26_630Z-debug.log](https://github.com/salesforce/lwc-jest/files/2982164/2019-03-19T07_56_26_630Z-debug.log)
 

npm install @salesforce/lwc-jest --save-dev

> deasync@0.1.12 install D:\PracticeLightningWebComponent\LightningWebComponentTestServices\LightningWebComponentTestServices\node_modules\deasync
> node ./build.js


D:\PracticeLightningWebComponent\LightningWebComponentTestServices\LightningWebComponentTestServices\node_modules\deasync>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0".
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\PracticeLightningWebComponent\LightningWebComponentTestServices\LightningWebComponentTestServices\node_modules\deasync
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed
npm WARN @lwc/jest-transformer@0.34.7 requires a peer of @lwc/compiler@0.34.x but none is installed. You must install peer dependencies yourself.
npm WARN @lwc/jest-transformer@0.34.7 requires a peer of @lwc/engine@0.34.x but none is installed. You must install peer dependencies yourself.
npm WARN lightningwebcomponenttestservices@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.12 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.1.12 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dell\AppData\Roaming\npm-cache\_logs\2019-03-19T07_56_26_630Z-debug.log 

Please take a look. 
Thanks,
Dilip Bhambhani

**Comment by muenzpraeger** [comment]
Can you run first `npm install --global --production windows-build-tools`, and see if that resolves the issue?

**Comment by pmdartus** [comment]
The `deasync` module requires to compile C++ on install. The last time I tried, I was able to install on windows lwc-jest by following these steps: https://github.com/nodejs/node-gyp#on-windows.

@dilipbhambhani Based on the install logs it appears that windows-build-tools are not up to date. Can you verify if following the steps above fixe your issue? If it's the case we will update README.

**Comment by Mahakb** [comment]
Hi @muenzpraeger 

Even after running  the command, while installing still getting this error:-

'jest' is not recognized as an internal or external command,
operable program or batch file.

Finished running all tests. Starting watch mode.
'jest' is not recognized as an internal or external command,
operable program or batch file.

'jest' is not recognized as an internal or external command,
operable program or batch file.

'jest' is not recognized as an internal or external command,
operable program or batch file.

'jest' is not recognized as an internal or external command,
operable program or batch file.

'jest' is not recognized as an internal or external command,
operable program or batch file.

Starting Jest in Watch mode failed too many times and has been stopped.
 see troubleshooting: https://github.com/jest-community/vscode-jest/blob/master/README.md#troubleshooting

![error](https://user-images.githubusercontent.com/15336805/54809289-d8fa2680-4ca8-11e9-96f8-167b055ec158.png)

**Comment by pmdartus** [comment]
@Mahakb were you able to install `lwc-jest` properly? Is the `lwc-jest` command working as expected?

**Comment by Mahakb** [comment]
No.. With that too I am getting below error message:-

'lwc-jest' is not recognized as an internal or external command,

**Comment by pmdartus** [comment]
Can you share the commands you run and the associated logs, it should make debugging easier?
Also what is your version of npm and node?

**Comment by Mahakb** [comment]
I started with :- 
- npm  install --global --production windows-build-tools
that  gave successfull python installation message.. 
 

- Post that I tried installing JEST Extension and I got the error log I shared.

- When I run 'lwc-jest', I get unrecognised command.

node--version give me version :-  v10.15.1

**Comment by pmdartus** [comment]
The `lwc-jest` is not installed globally if added to the `package.json` and will not be in your path. You should be able to run `lwc-jest` by either adding it to `script` in the `package.json` or run the following command:

```js
./node_modules/.bin/lwc-jest
```

**Comment by dilipbhambhani** [comment]
> The `deasync` module requires to compile C++ on install. The last time I tried, I was able to install on windows lwc-jest by following these steps: https://github.com/nodejs/node-gyp#on-windows.
> 
> @dilipbhambhani Based on the install logs it appears that windows-build-tools are not up to date. Can you verify if following the steps above fixe your issue? If it's the case we will update README.

Hi @muenzpraeger , Sorry for delay replay and thanks for providing this solution. I have "**npm install --global --production windows-build-tools**" command and successfully configure this tool and run "**npm install @salesforce/lwc-jest --save-dev**". But vscode is showing below error : 


npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).

> deasync@0.1.12 install D:\PracticeLightningWebComponent\LightningWebComponentTestServices\LightningWebComponentTestServices\node_modules\deasync
> node ./build.js


D:\PracticeLightningWebComponent\LightningWebComponentTestServices\LightningWebComponentTestServices\node_modules\deasync>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0".
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\PracticeLightningWebComponent\LightningWebComponentTestServices\LightningWebComponentTestServices\node_modules\deasync
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed
npm WARN lightningwebcomponenttestservices@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.12 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.1.12 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dell\AppData\Roaming\npm-cache\_logs\2019-03-22T12_01_25_117Z-debug.log

I am attaching the log file. Please take a look. 
[2019-03-22T12_01_25_117Z-debug.log](https://github.com/salesforce/lwc-jest/files/2996420/2019-03-22T12_01_25_117Z-debug.log)

Thanks,
Dilip Bhambhani

**Comment by trevor-bliss** [comment]
@Mahakb Were you able to verify if lwc-jest was installed in your workspace? 

Please re-run the following three commands from your project root and let us know what happens:

```bash
npm install --global --production windows-build-tools
yarn add -D @salesforce/lwc-jest
./node_modules/@salesforce/lwc-jest/bin/lwc-jest
```

**Comment by Mahakb** [comment]
@trevor-bliss  Actually, I was able to install the JEST in my workspace, but still not able to run JEST 
Following is the screenshot of the error:- See if you can help .

![image](https://user-images.githubusercontent.com/15336805/55015272-8c00b200-5012-11e9-9a3f-4d280d07f780.png)

**Comment by trevor-bliss** [comment]
@dilipbhambhani If `npm install --global --production windows-build-tools` did not work for you, there are alternate steps here: https://github.com/nodejs/node-gyp#on-windows.

That link is actually from the DeAsync README which has some more info for installation instructions: https://github.com/abbr/deasync#installation.

I'm also working on upgrading this transitive dependency soon so hopefully it will resolve itself in the next version upgrade of lwc-jest coming soon.

**Comment by trevor-bliss** [comment]
@Mahakb lwc-jest and jest are two separate projects. lwc-jest is essentially a wrapper around jest that handles configuration and dependency management. 

That error says it's looking for a file it cannot find. Does that file exist in your workspace?

`node_modules\@salesforce\lwc-jest\src\index.js`

**Comment by dilipbhambhani** [comment]
> npm install --global --production windows-build-tools

Thanks, @trevor-bliss for your response, I have re-run "**npm install --global --production windows-build-tools**" command and then run "**npm install @salesforce/lwc-jest --save-dev**" command. But now vscode is showing below error : 
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm WARN lightningwebcomponenttestservices@1.0.0 No description
npm WARN lightningwebcomponenttestservices@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @salesforce/lwc-jest@0.4.12
updated 1 package and audited 21731 packages in 70.751s
found 65 vulnerabilities (62 low, 3 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details

Please take a look and let us know what we need to do for it.
Thanks,
Dilip Bhambhani

**Comment by trevor-bliss** [comment]
@dilipbhambhani That looks like a successful install to me. The other warnings are for other dependencies that appear to be only warnings and not errors.

Now merge the following scripts with any existing ones you have in your `package.json`:
```
{
    "scripts": {
        "test:unit": "lwc-jest",
        "test:unit:watch": "lwc-jest --watch",
        "test:unit:debug": "lwc-jest --debug"
    }
}
```

And from the command line run:

```
npm run test:unit
```

**Comment by Mahakb** [comment]
@trevor-bliss , Finally it sucessfully running in my system. the issue was with JEST, It required me to install Python. Post that , I installed Jest Extension from the marketplace . And then this @salesforce/jest dependency. 

Thanks for your help.

**Comment by trevor-bliss** [comment]
I'm glad you figured it out @Mahakb! I'll close this issue out now.

**Comment by trevor-bliss** [comment]
I'd also like to point out that after this PR https://github.com/salesforce/lwc-jest/pull/44, the transitive dependency on `deasync` is upgraded to 0.1.14 which may fix the issue for future users.
